FC = g++
PRAC1 = Prac1
PRAC2 = Prac2
PRAC3 = Prac3
PRAC4 = Prac4
PRAC5 = Prac5
PRAC6 = Prac6
PRAC7 = Prac7
PRAC8 = Prac8
PRAC9 = Prac9
PRAC10 = Prac10

all:
	$(FC) $(PRAC1).cpp -o $(PRAC1)
	$(FC) $(PRAC2).cpp -o $(PRAC2)
	$(FC) $(PRAC3).cpp -o $(PRAC3)
	$(FC) $(PRAC4).cpp -o $(PRAC4)
	$(FC) $(PRAC5).cpp -o $(PRAC5)
	$(FC) $(PRAC6).cpp -o $(PRAC6)
	$(FC) $(PRAC7).cpp -o $(PRAC7)
	$(FC) $(PRAC8).cpp -o $(PRAC8)
	$(FC) $(PRAC9).cpp -o $(PRAC9)
	$(FC) $(PRAC10).cpp -o $(PRAC10)

clean:
	rm -f $(PRAC1)
	rm -f $(PRAC2)
	rm -f $(PRAC3)
	rm -f $(PRAC4)
	rm -f $(PRAC5)
	rm -f $(PRAC6)
	rm -f $(PRAC7)
	rm -f $(PRAC8)
	rm -f $(PRAC9)
	rm -f $(PRAC10)
